CREATE TABLE ALBUM (
  ID INTEGER AUTO_INCREMENT,
  MUSIC_GROUP VARCHAR(30),
  NAMEALBUM VARCHAR(30),
  YEAR VARCHAR(30),
  PRIMARY KEY (ID)
);
CREATE TABLE TRACK (
  ID INTEGER AUTO_INCREMENT,
  TITLE VARCHAR(30),
  SINGER VARCHAR(30),
  ALBUM_ID INTEGER NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_ALBUM FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM (ID)
);
