CREATE TABLE TRACKS (
  ID INTEGER AUTO_INCREMENT,
  NAMETRACK VARCHAR(30),
  CONTRACTOR VARCHAR(30),
  ALBUM_ID INTEGER,
  PRIMARY KEY (ID),
  CONSTRAINT FK_ID_TRACKS FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM (ID) ON DELETE CASCADE
);
